version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'games-dev'
      MYSQL_USER: 'usr-games'
      MYSQL_PASSWORD: 'pwd-games'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - app-network
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

networks:
  app-network:
    driver: bridge